"""Minimum-detectable-effect power analysis for the primary out-of-sample test.

Quantifies the bound on the null: how large a graded, species-level effect the standing pipeline
would have detected. A known effect of size beta (standardised logit units, the units of the
reported GLM coefficients) is planted onto the real per-cell scores — y' = sigmoid(logit(y) +
beta * z), with z the standardised visual distance — and the unchanged leave-whole-group-out CV
plus paired group-bootstrap (criterion (ii) of the decision rule) is asked whether it detects the
plant at p < 0.05. Each replicate resamples whole species groups with replacement, so the real
group structure, support weights and residual noise carry through untouched; cells with y = 0
barely respond to the plant, which keeps the estimate conservative. The MDE is the smallest beta
detected in at least 80% of replicates. Writes outputs/power/mde.csv and tables/mde.tex.

Run: PYTHONPATH=. python -m src.analysis.power [--reps N] [--config configs/default.yaml]
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd

from src.analysis.cross_val import _SCHEME_COLUMN, _summarise, oos_predictions
from src.analysis.regression import _num
from src.config import Config
from src.io import read_parquet

BETA_GRID = (0.0, 0.30, 0.75, 1.00, 1.25, 1.50, 1.75, 2.00)
PLANT_COL = "visual_distance"
TARGET = "pDetA"
POWER_BAR = 0.80
_EPS = 1e-3


def _plant(rows: pd.DataFrame, beta: float) -> pd.DataFrame:
    """Return a copy of rows with a beta-sized effect of PLANT_COL added to TARGET on the logit scale."""
    out = rows.copy()
    z = _num(out[PLANT_COL])
    z = (z - z.mean()) / (z.std() or 1.0)
    y = _num(out[TARGET]).clip(_EPS, 1.0 - _EPS)
    logit = np.log(y / (1.0 - y)) + beta * z.fillna(0.0)
    out[TARGET] = 1.0 / (1.0 + np.exp(-logit))
    return out


SUBSAMPLE = 0.9


def _resample_groups(rows: pd.DataFrame, group_col: str, rng: np.random.Generator) -> pd.DataFrame:
    """Subsample whole groups without replacement (SUBSAMPLE of them per replicate).

    Sampling with replacement would duplicate groups, and leave-one-group-out would then hold out a
    group whose twin remains in training — leakage that inflates the false-positive rate. Without
    replacement there are no twins; the slightly smaller design makes the power estimate conservative.
    """
    uniq = rows[group_col].astype(str).unique()
    keep = rng.choice(uniq, size=max(2, int(round(SUBSAMPLE * len(uniq)))), replace=False)
    return rows[rows[group_col].astype(str).isin(keep)].reset_index(drop=True)


def run(config: Config | None = None, reps: int = 60, betas: tuple[float, ...] = BETA_GRID) -> Path:
    """Estimate detection power per beta and scheme; write the CSV and the appendix table."""
    config = config or Config()
    outputs = config.paths.outputs_root
    table = outputs / "features_diff.parquet"
    rows = read_parquet(table if table.exists() else outputs / "features.parquet")
    rows = rows[_num(rows[TARGET]).notna()].reset_index(drop=True)

    records = []
    for scheme, group_col in _SCHEME_COLUMN.items():
        for beta in betas:
            rng = np.random.default_rng(config.seed + int(beta * 1000))
            hits, deltas = 0, []
            for _ in range(reps):
                sample = _resample_groups(rows, group_col, rng)
                planted = _plant(sample, beta)
                cv = oos_predictions(planted, TARGET, group_col, config)
                if cv.empty:
                    continue
                summ = _summarise(cv, config)
                row = summ[summ["target"] == TARGET].iloc[0]
                hits += int(row["p_value"] < 0.05)
                deltas.append(float(row["delta"]))
            records.append({
                "scheme": scheme, "beta": beta, "reps": reps,
                "power": round(hits / reps, 3),
                "mean_delta_mae": round(float(np.mean(deltas)), 4) if deltas else float("nan"),
            })
            print(f"{scheme} beta={beta}: power={hits / reps:.2f}")

    out = pd.DataFrame(records)
    outdir = outputs / "power"
    outdir.mkdir(parents=True, exist_ok=True)
    csv = outdir / "mde.csv"
    out.to_csv(csv, index=False)
    _write_table(out, config)
    print(f"power analysis -> {csv}")
    return csv


def _mde(out: pd.DataFrame, scheme: str) -> float:
    """Smallest beta with power >= POWER_BAR for scheme (NaN if none reaches it)."""
    hit = out[(out["scheme"] == scheme) & (out["power"] >= POWER_BAR)]
    return float(hit["beta"].min()) if not hit.empty else float("nan")


def _write_table(out: pd.DataFrame, config: Config) -> None:
    """Emit tables/mde.tex for the appendix."""
    lines = [
        "% generated by src/analysis/power.py --- do not edit by hand",
        "\\begin{table}[htbp]\\centering",
        "  \\caption[Minimum detectable effect]{Planted-effect power of the primary out-of-sample test",
        "  (criterion (ii), detection, " + str(int(out['reps'].iloc[0])) + " replicates per cell): the fraction of",
        "  replicates in which a species-level effect of standardised size $\\beta$, planted on the real scores,",
        "  is detected at $p<0.05$. $\\Delta$MAE is the mean out-of-sample gain the plant produces. Cells at",
        "  $\\texttt{pDetA}=0$ barely respond to the plant, so these estimates are conservative.}",
        "  \\label{tab:mde}",
        "  \\footnotesize",
        "  \\begin{tabular}{l" + "c" * out["beta"].nunique() + "}",
        "    \\toprule",
        "    & \\multicolumn{" + str(out["beta"].nunique())
        + "}{c}{planted effect size $\\beta$ (standardised logit units)} \\\\",
        "    Scheme & " + " & ".join(f"{b:.2f}" for b in sorted(out["beta"].unique())) + " \\\\",
        "    \\midrule",
    ]
    for scheme in ("species", "location"):
        sub = out[out["scheme"] == scheme].sort_values("beta")
        lines.append(f"    leave-{scheme}-out power & " + " & ".join(f"{p:.2f}" for p in sub["power"]) + " \\\\")
        lines.append("    \\quad mean $\\Delta$MAE at $\\beta$ & "
                     + " & ".join(f"{d:+.3f}" for d in sub["mean_delta_mae"]) + " \\\\")
    lines += ["    \\bottomrule", "  \\end{tabular}", "\\end{table}", ""]
    path = Path("report/dissertation/tables/mde.tex")
    path.write_text("\n".join(lines))
    print(f"table -> {path}")


def main() -> None:
    """CLI entry point."""
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--config", default=None, help="optional YAML config")
    ap.add_argument("--reps", type=int, default=60, help="replicates per (scheme, beta)")
    args = ap.parse_args()
    run(Config.load(args.config), reps=args.reps)


if __name__ == "__main__":
    main()
