"""Export the pipeline's results into the dissertation.

Reads the generated artifacts under ``outputs/`` (which is git-ignored) and writes committed,
dissertation-facing files under ``report/dissertation/``:

* ``results_summary.md`` --- a human-readable rollup of every headline number (so the results survive
  even though ``outputs/*.parquet`` never enters git), and
* ``tables/{gate1_measurement,coefficients,cv_validation}.tex`` --- ``booktabs`` fragments that
  ``chapters/results.tex`` ``\\input``s straight into the Results chapter.

Run: ``PYTHONPATH=. python -m src.analysis.report [--config configs/default.yaml]``
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd

from src.analysis.cross_val import _summarise
from src.analysis.regression import CONFIDENCE_COLS, DISTANCE_COLS, TARGETS
from src.config import Config
from src.io import read_parquet

_COEF_ROWS = (*DISTANCE_COLS, *CONFIDENCE_COLS, "log_area", "clutter", "is_night_ir", "log_support")
_ROW_LABEL = {
    "taxonomic_distance": "Taxonomic distance",
    "temporal_gap": "Temporal gap",
    "visual_distance": "Visual distance",
    "environment_distance": "Environment distance",
    "conf_atc_coverage": "ATC coverage (after-running)",
    "conf_mean_score": "Mean masklet score",
    "conf_median_score": "Median masklet score",
    "conf_frame_coverage": "Frame coverage",
    "log_area": "log(area)",
    "clutter": "Clutter",
    "is_night_ir": "Night / IR",
    "log_support": "log(support)",
}


def _fmt(x: float, nd: int = 3) -> str:
    return "--" if x is None or (isinstance(x, float) and np.isnan(x)) else f"{x:.{nd}f}"


def _gate1(outputs: Path, tag: str = "") -> tuple[dict, str]:
    """Support-weighted per-cell aggregate from scores.parquet (+ VEval AP/TETA if persisted)."""
    df = read_parquet(outputs / "scores.parquet")
    scored = df[df["pDetA"].notna()]
    w = scored["n_frames"].to_numpy(dtype=float)
    w = w if w.sum() > 0 else None
    agg = {m: float(np.average(scored[m], weights=w)) for m in ("pDetA", "pAssA", "pHOTA")}
    agg |= {"n_cells": int(len(df)), "n_scored": int(len(scored))}
    veval = outputs / "veval_summary.json"
    agg["veval"] = json.loads(veval.read_text()) if veval.exists() else {}

    rows = "\n".join(
        f"    {name} & {_fmt(agg[name])} \\\\" for name in ("pDetA", "pAssA", "pHOTA")
    )
    where = "the SA-FARI test split" if not tag else "the pooled train+test set"
    tex = (
        "% generated by src/analysis/report.py --- do not edit by hand\n"
        "\\begin{table}[htbp]\\centering\n"
        f"  \\caption{{Zero-shot SAM\\,3 on {where} --- support-weighted mean over "
        f"{agg['n_scored']} scored cells (of {agg['n_cells']}).}}\n"
        f"  \\label{{tab:gate1{tag}}}\n"
        "  \\begin{tabular}{lr}\n    \\toprule\n"
        "    Metric (mask) & Value \\\\\n    \\midrule\n"
        f"{rows}\n"
        "    \\bottomrule\n  \\end{tabular}\n\\end{table}\n"
    )
    return agg, tex


def _coefficients(outputs: Path, tag: str = "") -> tuple[dict, str]:
    """Standardised GLM coefficients (+ 95% CI) for both targets, side by side."""
    coefs = {t: pd.read_csv(outputs / "models" / f"{t}_coef.csv", index_col=0) for t in TARGETS}
    present = [r for r in _COEF_ROWS if any(r in coefs[t].index for t in TARGETS)]
    summary = {
        t: {r: float(coefs[t].loc[r, "coef"]) for r in present if r in coefs[t].index} for t in TARGETS
    }

    def cell(t: str, r: str) -> str:
        if r not in coefs[t].index:
            return "--"
        row = coefs[t].loc[r]
        lo, hi = row.get("ci_lo"), row.get("ci_hi")
        if lo is None or hi is None or pd.isna(lo) or pd.isna(hi):
            return f"{row['coef']:.3f}"
        return f"{row['coef']:.3f} [{lo:.2f}, {hi:.2f}]"

    def excludes_zero(t: str, r: str) -> bool:
        if r not in coefs[t].index:
            return False
        lo, hi = coefs[t].loc[r].get("ci_lo"), coefs[t].loc[r].get("ci_hi")
        return bool(lo is not None and hi is not None and not pd.isna(lo) and (lo > 0 or hi < 0))

    distances_signif = [r for r in DISTANCE_COLS if any(excludes_zero(t, r) for t in TARGETS)]
    zero_note = (
        " Every distance's CI spans zero." if not distances_signif else ""
    )

    body = "\n".join(
        f"    {_ROW_LABEL.get(r, r)} & {cell('pDetA', r)} & {cell('pAssA', r)} \\\\" for r in present
    )
    tex = (
        "% generated by src/analysis/report.py --- do not edit by hand\n"
        "\\begin{table}[htbp]\\centering\n"
        "  \\caption{Standardised logit-GLM coefficients with \\emph{group-cluster-bootstrap} 95\\% CIs "
        "(resampling whole species / locations, so the interval respects pseudo-replication and the "
        f"support weighting), for detection (pDetA) and association (pAssA).{zero_note}}}\n"
        f"  \\label{{tab:coefficients{tag}}}\n"
        "  \\begin{tabular}{lcc}\n    \\toprule\n"
        "    Factor & pDetA coef.\\ [CI] & pAssA coef.\\ [CI] \\\\\n    \\midrule\n"
        f"{body}\n"
        "    \\bottomrule\n  \\end{tabular}\n\\end{table}\n"
    )
    return summary, tex


def _cv(outputs: Path, config: Config | None = None, tag: str = "") -> tuple[pd.DataFrame, str]:
    """Grouped-CV out-of-sample MAE vs a mean-predictor baseline, with a group-bootstrap significance test."""
    summary = _summarise(read_parquet(outputs / "validation" / "cv_results.parquet"), config)
    summary = summary.sort_values(["group_scheme", "target"]).reset_index(drop=True)
    body = "\n".join(
        f"    {r.group_scheme} & {r.target} & {int(r.n)} & {r.mae:.3f} & {r.baseline_mae:.3f}"
        f" & {r.delta:+.3f}~[{r.delta_lo:+.3f},\\,{r.delta_hi:+.3f}] & {r.p_value:.2f} \\\\"
        for r in summary.itertuples()
    )
    any_signif = bool(summary["significant"].any()) if "significant" in summary else False
    verdict = "" if any_signif else " No hold-out's gain is significant."
    tex = (
        "% generated by src/analysis/report.py --- do not edit by hand\n"
        "\\begin{table}[htbp]\\centering\n"
        "  \\caption{Out-of-sample error: whole-group hold-out (leave-species-out / "
        "leave-location-out) vs a mean predictor. $\\Delta$ is the MAE gain over baseline; its bracketed "
        "95\\% CI and one-sided $p$ come from a paired bootstrap resampling whole held-out groups."
        f"{verdict}}}\n"
        f"  \\label{{tab:cv{tag}}}\n"
        "  \\begin{tabular}{llrrrcr}\n    \\toprule\n"
        "    Hold-out & Target & $n$ & MAE & Baseline & $\\Delta$~[95\\% CI] & $p$ \\\\\n    \\midrule\n"
        f"{body}\n"
        "    \\bottomrule\n  \\end{tabular}\n\\end{table}\n"
    )
    return summary, tex


_DIFFICULTY_LABELS = {
    "log_support_only": "$\\log$(support) only",
    "log_area_only": "$\\log$(area) only \\emph{[size]}",
    "lowlight_only_no_size": "Low-light only (no size)",
    "lowlight_plus_size": "Low-light $+$ size",
}


def _difficulty(outputs: Path, tag: str = "") -> tuple[dict, str]:
    """Nested size-decomposition of the intrinsic-difficulty test: is the OOS gain size or low-light?"""
    summary = json.loads((outputs / "difficulty_experiment_summary.json").read_text())

    def cell(sch: dict) -> str:
        if not sch:
            return "--"
        return f"{sch['delta']:+.3f}~[{sch['delta_lo']:+.3f},\\,{sch['delta_hi']:+.3f}]~({sch['p_value']:.3f})"

    body = "\n".join(
        f"    {_DIFFICULTY_LABELS.get(d['model'], d['model'])} & {cell(d['schemes'].get('species', {}))}"
        f" & {cell(d['schemes'].get('location', {}))} \\\\"
        for d in summary.get("decomposition", [])
    )
    tex = (
        "% generated by src/analysis/report.py --- do not edit by hand\n"
        "\\begin{table}[htbp]\\centering\n"
        "  \\caption{Nested size decomposition of the intrinsic-difficulty test (detection, "
        f"{summary.get('n_pdeta_cells', '?')} cells). Each entry is the out-of-sample MAE gain over a "
        "mean-predictor baseline, $\\Delta$~[95\\% CI]~($p$), under leave-species-out and leave-location-out. "
        "The entire gain sits in the size covariate ($\\log$-area); low-light \\emph{alone} does not validate "
        "--- the difficulty signals only pass the bar by riding on size.}\n"
        f"  \\label{{tab:difficulty{tag}}}\n"
        "  \\begin{tabular}{lcc}\n    \\toprule\n"
        "    Model & Leave-species-out $\\Delta$~[CI]~($p$) & Leave-location-out $\\Delta$~[CI]~($p$) \\\\\n"
        "    \\midrule\n"
        f"{body}\n"
        "    \\bottomrule\n  \\end{tabular}\n\\end{table}\n"
    )
    return summary, tex


def _fp(outputs: Path, tag: str = "") -> tuple[dict, str]:
    """False-positive (hallucination) analysis on hard negatives: the size-independent visual correlate."""
    s = json.loads((outputs / "false_positives_summary.json").read_text())

    def cor(d: dict, stat: str = "pearson_r") -> str:
        r = d.get(stat, d.get("partial_r"))
        sig = "significant" if d.get("significant") else "n.s."
        return f"${r:+.2f}$ & $[{d['ci_lo']:+.2f},\\,{d['ci_hi']:+.2f}]$ & {sig}"

    oos = s["fp_predictor_oos"]
    rows = [
        f"    FP rate vs taxonomic distance & {cor(s['fp_vs_taxonomic'])} \\\\",
        f"    FP rate vs \\textbf{{visual distance}} & {cor(s['fp_vs_visual'])} \\\\",
        f"    \\quad visual, size-controlled (partial) & {cor(s['fp_vs_visual_size_controlled'], 'partial_r')} \\\\",
        f"    FP rate vs animal size & {cor(s['fp_vs_size'])} \\\\",
        f"    leave-species-out OOS gain & ${oos['delta']:+.3f}$ & $[{oos['ci_lo']:+.3f},\\,{oos['ci_hi']:+.3f}]$"
        f" & $p={oos['p_value']:.3f}$ \\\\",
    ]
    tex = (
        "% generated by src/analysis/report.py --- do not edit by hand\n"
        "\\begin{table}[htbp]\\centering\n"
        f"  \\caption{{False positives on the {s['n_probes']} hard negatives ({s['n_species']} species): the "
        f"overall hallucination rate is {s['overall_fp_rate'] * 100:.1f}\\%. More visually distinctive species "
        "hallucinate \\emph{less} --- a real, size-independent correlate --- but it does not validate out of "
        "sample (leave-species-out $p=0.053$), so it is a correlate, not a predictor.}\n"
        f"  \\label{{tab:fp{tag}}}\n"
        "  \\begin{tabular}{lccc}\n    \\toprule\n"
        "    Test (species-level) & statistic & 95\\% CI & verdict \\\\\n    \\midrule\n"
        f"{chr(10).join(rows)}\n"
        "    \\bottomrule\n  \\end{tabular}\n\\end{table}\n"
    )
    return s, tex


def _ablation(outputs: Path, tag: str = "") -> tuple[pd.DataFrame, str]:
    """Factor-drop / +size / -support ablation (detection): only size moves the score."""
    d = pd.read_csv(outputs / "ablations" / "factor_ablation.csv")
    body = "\n".join(
        f"    {r.design} & {r.pseudo_r2:.3f} & ${r.oos_species_delta:+.3f}$~($p{{=}}{r.oos_species_p:.2f}$)"
        f" & ${r.oos_location_delta:+.3f}$~($p{{=}}{r.oos_location_p:.2f}$) \\\\"
        for r in d.itertuples()
    )
    tex = (
        "% generated by src/analysis/report.py --- do not edit by hand\n"
        "\\begin{table}[htbp]\\centering\n"
        "  \\caption{Factor ablation for detection (\\texttt{pDetA}): McFadden pseudo-$R^2$ and the "
        "out-of-sample MAE gain over a mean baseline under leave-species-out (LSO) and leave-location-out "
        "(LLO). Dropping any single distance barely changes the fit or the (null) out-of-sample gain --- no "
        "factor carries signal; only adding the animal-size covariate moves the score.}\n"
        f"  \\label{{tab:ablation{tag}}}\n"
        "  \\begin{tabular}{lccc}\n    \\toprule\n"
        "    Design & pseudo-$R^2$ & LSO $\\Delta$~($p$) & LLO $\\Delta$~($p$) \\\\\n    \\midrule\n"
        f"{body}\n"
        "    \\bottomrule\n  \\end{tabular}\n\\end{table}\n"
    )
    return d, tex


def _variance(outputs: Path, tag: str = "") -> tuple[pd.DataFrame, str]:
    """LMG/Shapley unique R^2 + VIF per distance (detection): tiny total, no collinearity."""
    d = pd.read_csv(outputs / "ablations" / "variance_partition.csv")
    d = d[d["target"] == "pDetA"]
    labels = {"taxonomic_distance": "Taxonomic", "visual_distance": "Visual",
              "environment_distance": "Environment", "temporal_gap": "Temporal"}
    body = "\n".join(
        f"    {labels.get(r.factor, r.factor)} & {r.lmg_r2:.3f} & {r.share * 100:.0f}\\% &"
        f" {'--' if pd.isna(r.vif) else f'{r.vif:.2f}'} \\\\"
        for r in d.itertuples()
    )
    total = float(d["lmg_r2"].sum())
    tex = (
        "% generated by src/analysis/report.py --- do not edit by hand\n"
        "\\begin{table}[htbp]\\centering\n"
        "  \\caption{Variance partition for detection (\\texttt{pDetA}): each distance's unique share of "
        f"$R^2$ (LMG/Shapley) and its VIF. The four distances together explain only $\\approx{total * 100:.0f}"
        "\\%$ of the variance, no factor dominates, and every VIF~$\\approx1$ --- the null is not masked by "
        "collinearity.}\n"
        f"  \\label{{tab:variance{tag}}}\n"
        "  \\begin{tabular}{lccc}\n    \\toprule\n"
        "    Factor & unique $R^2$ & share & VIF \\\\\n    \\midrule\n"
        f"{body}\n"
        "    \\bottomrule\n  \\end{tabular}\n\\end{table}\n"
    )
    return d, tex


def _coverage(outputs: Path) -> dict:
    """Per-distance non-null coverage in the merged feature table."""
    f = read_parquet(outputs / "features.parquet")
    return {"n_rows": int(len(f))} | {
        c: int(f[c].notna().sum()) for c in (*DISTANCE_COLS, *CONFIDENCE_COLS, "log_area") if c in f.columns
    }


def export(config: Config | None = None) -> Path:
    """Write the dissertation results summary + table fragments; return the summary path."""
    cfg = config or Config()
    outputs = cfg.paths.outputs_root
    dissertation = cfg.paths.outputs_root.parent / "report" / "dissertation"
    tables = dissertation / "tables"
    tables.mkdir(parents=True, exist_ok=True)
    # Experiment tag suffixes the output filenames so a second experiment does not clobber the first;
    # "location" keeps the unsuffixed names of the primary (already-committed) location tables.
    tag = "" if cfg.experiment == "location" else f"_{cfg.experiment}"

    lines = ["# Results summary (generated by `src/analysis/report.py`)", ""]

    if (outputs / "scores.parquet").exists():
        agg, tex = _gate1(outputs, tag)
        (tables / f"gate1_measurement{tag}.tex").write_text(tex)
        lines += [
            "## Gate 1 --- measurement (support-weighted cell means, mask)",
            f"- pDetA {agg['pDetA']:.3f} | pAssA {agg['pAssA']:.3f} | pHOTA {agg['pHOTA']:.3f}"
            f"  ({agg['n_scored']}/{agg['n_cells']} cells scored)",
            f"- VEval dataset_results: {json.dumps(agg['veval'])[:400]}",
            "",
        ]

    if (outputs / "features.parquet").exists():
        cov = _coverage(outputs)
        lines += [
            "## Feature coverage (non-null / rows)",
            "  ".join(f"{k}={v}" for k, v in cov.items()),
            "",
        ]

    if all((outputs / "models" / f"{t}_coef.csv").exists() for t in TARGETS):
        summary, tex = _coefficients(outputs, tag)
        (tables / f"coefficients{tag}.tex").write_text(tex)
        lines += ["## Gate 2 --- fitted law (standardised coefficients, group-cluster-bootstrap 95% CI)"]
        coefs = {t: pd.read_csv(outputs / "models" / f"{t}_coef.csv", index_col=0) for t in TARGETS}
        for t in TARGETS:
            parts = []
            for k, v in summary[t].items():
                lo, hi = coefs[t].loc[k].get("ci_lo"), coefs[t].loc[k].get("ci_hi")
                ci = "" if lo is None or pd.isna(lo) else f" [{lo:+.2f},{hi:+.2f}]"
                parts.append(f"{k} {v:+.3f}{ci}")
            lines.append(f"- {t}: " + ", ".join(parts))
        lines.append("")

    if (outputs / "validation" / "cv_results.parquet").exists():
        summary, tex = _cv(outputs, cfg, tag)
        (tables / f"cv_validation{tag}.tex").write_text(tex)
        lines += ["## Gate 2 --- out-of-sample validation (group-bootstrap significance test)"]
        for r in summary.itertuples():
            verdict = "significant" if getattr(r, "significant", False) else "n.s."
            lines.append(
                f"- {r.group_scheme}/{r.target}: dMAE {r.delta:+.4f} "
                f"[{r.delta_lo:+.4f}, {r.delta_hi:+.4f}] p={r.p_value:.3f} (n={int(r.n)}) --- {verdict}"
            )
        lines.append("")

    if (outputs / "difficulty_experiment_summary.json").exists():
        dsum, tex = _difficulty(outputs, tag)
        (tables / f"difficulty{tag}.tex").write_text(tex)
        lines += ["## Difficulty / size-decomposition (detection)",
                  f"- verdict: {dsum.get('verdict', '')}",
                  f"- {dsum.get('decomposition_verdict', '')}"]
        for d in dsum.get("decomposition", []):
            lines.append(f"- {d['model']}: " + ", ".join(
                f"{sc} dMAE {v.get('delta')} p={v.get('p_value')}" for sc, v in d["schemes"].items()))
        lines.append("")

    if (outputs / "false_positives_summary.json").exists():
        fpsum, tex = _fp(outputs, tag)
        (tables / f"false_positives{tag}.tex").write_text(tex)
        oos = fpsum["fp_predictor_oos"]
        lines += [
            "## Detection precision --- false positives (hallucination)",
            f"- overall FP rate {fpsum['overall_fp_rate']:.3f} on {fpsum['n_probes']} hard negatives "
            f"({fpsum['n_species']} species)",
            f"- fp vs visual r={fpsum['fp_vs_visual']['pearson_r']:.3f} (size-controlled partial "
            f"{fpsum['fp_vs_visual_size_controlled']['partial_r']:.3f})",
            f"- leave-species-out OOS gain {oos['delta']:+.4f} p={oos['p_value']:.3f} --- "
            f"{'significant' if oos['significant'] else 'n.s. (a correlate, not a predictor)'}",
            "",
        ]

    if (outputs / "ablations" / "variance_partition.csv").exists():
        _, tex = _variance(outputs, tag)
        (tables / f"variance{tag}.tex").write_text(tex)
        lines += ["## Variance partition (unique R^2 + VIF, detection)", ""]
    if (outputs / "ablations" / "factor_ablation.csv").exists():
        _, tex = _ablation(outputs, tag)
        (tables / f"ablations{tag}.tex").write_text(tex)
        lines += ["## Factor ablation (detection)", ""]

    summary_path = dissertation / f"results_summary{tag}.md"
    summary_path.write_text("\n".join(lines) + "\n")
    print(f"results -> {summary_path} (+ {tables}/*.tex)")
    return summary_path


def main() -> None:
    """CLI entry point."""
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--config", default=None, help="optional YAML config")
    args = ap.parse_args()
    export(Config.load(args.config))


if __name__ == "__main__":
    main()
