"""Export the pipeline's results into the dissertation.

Reads the generated artifacts under ``outputs/`` (which is git-ignored) and writes committed,
dissertation-facing files under ``report/dissertation/``:

* ``results_summary.md`` --- a human-readable rollup of every headline number (so the results survive
  even though ``outputs/*.parquet`` never enters git), and
* ``tables/{gate1_measurement,coefficients,cv_validation}.tex`` --- ``booktabs`` fragments that
  ``chapters/results.tex`` ``\\input``s straight into the Results chapter.

Run: ``PYTHONPATH=. python -m src.analysis.report [--config configs/default.yaml]``
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd

from src.analysis.cross_val import _summarise
from src.analysis.regression import DISTANCE_COLS, TARGETS
from src.config import Config
from src.io import read_parquet

_COEF_ROWS = (*DISTANCE_COLS, "clutter", "is_night_ir", "log_support")
_ROW_LABEL = {
    "taxonomic_distance": "Taxonomic distance",
    "temporal_gap": "Temporal gap",
    "visual_distance": "Visual distance",
    "environment_distance": "Environment distance",
    "clutter": "Clutter",
    "is_night_ir": "Night / IR",
    "log_support": "log(support)",
}


def _fmt(x: float, nd: int = 3) -> str:
    return "--" if x is None or (isinstance(x, float) and np.isnan(x)) else f"{x:.{nd}f}"


def _gate1(outputs: Path) -> tuple[dict, str]:
    """Support-weighted per-cell aggregate from scores.parquet (+ VEval AP/TETA if persisted)."""
    df = read_parquet(outputs / "scores.parquet")
    scored = df[df["pDetA"].notna()]
    w = scored["n_frames"].to_numpy(dtype=float)
    w = w if w.sum() > 0 else None
    agg = {m: float(np.average(scored[m], weights=w)) for m in ("pDetA", "pAssA", "pHOTA")}
    agg |= {"n_cells": int(len(df)), "n_scored": int(len(scored))}
    veval = outputs / "veval_summary.json"
    agg["veval"] = json.loads(veval.read_text()) if veval.exists() else {}

    rows = "\n".join(
        f"    {name} & {_fmt(agg[name])} \\\\" for name in ("pDetA", "pAssA", "pHOTA")
    )
    tex = (
        "% generated by src/analysis/report.py --- do not edit by hand\n"
        "\\begin{table}[t]\\centering\n"
        "  \\caption{Zero-shot SAM\\,3 on the SA-FARI test split --- support-weighted mean over "
        f"{agg['n_scored']} scored cells (of {agg['n_cells']}).}}\n"
        "  \\label{tab:gate1}\n"
        "  \\begin{tabular}{lr}\n    \\toprule\n"
        "    Metric (mask) & Value \\\\\n    \\midrule\n"
        f"{rows}\n"
        "    \\bottomrule\n  \\end{tabular}\n\\end{table}\n"
    )
    return agg, tex


def _coefficients(outputs: Path) -> tuple[dict, str]:
    """Standardised GLM coefficients (+ 95% CI) for both targets, side by side."""
    coefs = {t: pd.read_csv(outputs / "models" / f"{t}_coef.csv", index_col=0) for t in TARGETS}
    present = [r for r in _COEF_ROWS if any(r in coefs[t].index for t in TARGETS)]
    summary = {
        t: {r: float(coefs[t].loc[r, "coef"]) for r in present if r in coefs[t].index} for t in TARGETS
    }

    def cell(t: str, r: str) -> str:
        if r not in coefs[t].index:
            return "--"
        row = coefs[t].loc[r]
        return f"{row['coef']:.3f} [{row['ci_lo']:.2f}, {row['ci_hi']:.2f}]"

    body = "\n".join(
        f"    {_ROW_LABEL.get(r, r)} & {cell('pDetA', r)} & {cell('pAssA', r)} \\\\" for r in present
    )
    tex = (
        "% generated by src/analysis/report.py --- do not edit by hand\n"
        "\\begin{table}[t]\\centering\n"
        "  \\caption{Standardised logit-GLM coefficients (95\\% CI) for detection (pDetA) and "
        "association (pAssA).}\n"
        "  \\label{tab:coefficients}\n"
        "  \\begin{tabular}{lcc}\n    \\toprule\n"
        "    Factor & pDetA coef.\\ [CI] & pAssA coef.\\ [CI] \\\\\n    \\midrule\n"
        f"{body}\n"
        "    \\bottomrule\n  \\end{tabular}\n\\end{table}\n"
    )
    return summary, tex


def _cv(outputs: Path) -> tuple[pd.DataFrame, str]:
    """Grouped-CV out-of-sample MAE vs a mean-predictor baseline."""
    summary = _summarise(read_parquet(outputs / "validation" / "cv_results.parquet"))
    summary = summary.sort_values(["group_scheme", "target"]).reset_index(drop=True)
    body = "\n".join(
        f"    {r.group_scheme} & {r.target} & {int(r.n)} & {r.mae:.3f} & {r.baseline_mae:.3f}"
        f" & {(r.baseline_mae - r.mae):+.3f} \\\\"
        for r in summary.itertuples()
    )
    tex = (
        "% generated by src/analysis/report.py --- do not edit by hand\n"
        "\\begin{table}[t]\\centering\n"
        "  \\caption{Out-of-sample error: whole-group hold-out (leave-species-out / "
        "leave-location-out) vs a mean predictor. $\\Delta$ is the MAE improvement over baseline.}\n"
        "  \\label{tab:cv}\n"
        "  \\begin{tabular}{llrrrr}\n    \\toprule\n"
        "    Hold-out & Target & $n$ & MAE & Baseline & $\\Delta$ \\\\\n    \\midrule\n"
        f"{body}\n"
        "    \\bottomrule\n  \\end{tabular}\n\\end{table}\n"
    )
    return summary, tex


def _coverage(outputs: Path) -> dict:
    """Per-distance non-null coverage in the merged feature table."""
    f = read_parquet(outputs / "features.parquet")
    return {"n_rows": int(len(f))} | {
        c: int(f[c].notna().sum()) for c in DISTANCE_COLS if c in f.columns
    }


def export(config: Config | None = None) -> Path:
    """Write the dissertation results summary + table fragments; return the summary path."""
    cfg = config or Config()
    outputs = cfg.paths.outputs_root
    dissertation = cfg.paths.outputs_root.parent / "report" / "dissertation"
    tables = dissertation / "tables"
    tables.mkdir(parents=True, exist_ok=True)

    lines = ["# Results summary (generated by `src/analysis/report.py`)", ""]

    if (outputs / "scores.parquet").exists():
        agg, tex = _gate1(outputs)
        (tables / "gate1_measurement.tex").write_text(tex)
        lines += [
            "## Gate 1 --- measurement (support-weighted cell means, mask)",
            f"- pDetA {agg['pDetA']:.3f} | pAssA {agg['pAssA']:.3f} | pHOTA {agg['pHOTA']:.3f}"
            f"  ({agg['n_scored']}/{agg['n_cells']} cells scored)",
            f"- VEval dataset_results: {json.dumps(agg['veval'])[:400]}",
            "",
        ]

    if (outputs / "features.parquet").exists():
        cov = _coverage(outputs)
        lines += [
            "## Feature coverage (non-null / rows)",
            "  ".join(f"{k}={v}" for k, v in cov.items()),
            "",
        ]

    if all((outputs / "models" / f"{t}_coef.csv").exists() for t in TARGETS):
        summary, tex = _coefficients(outputs)
        (tables / "coefficients.tex").write_text(tex)
        lines += ["## Gate 2 --- fitted law (standardised coefficients)"]
        for t in TARGETS:
            lines.append(f"- {t}: " + ", ".join(f"{k} {v:+.3f}" for k, v in summary[t].items()))
        lines.append("")

    if (outputs / "validation" / "cv_results.parquet").exists():
        summary, tex = _cv(outputs)
        (tables / "cv_validation.tex").write_text(tex)
        lines += ["## Gate 2 --- out-of-sample validation (MAE vs baseline)"]
        for r in summary.itertuples():
            verdict = "beats" if r.mae < r.baseline_mae else "no signal"
            lines.append(
                f"- {r.group_scheme}/{r.target}: MAE {r.mae:.3f} vs {r.baseline_mae:.3f} "
                f"(n={int(r.n)}) --- {verdict}"
            )
        lines.append("")

    summary_path = dissertation / "results_summary.md"
    summary_path.write_text("\n".join(lines) + "\n")
    print(f"results -> {summary_path} (+ {tables}/*.tex)")
    return summary_path


def main() -> None:
    """CLI entry point."""
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--config", default=None, help="optional YAML config")
    args = ap.parse_args()
    export(Config.load(args.config))


if __name__ == "__main__":
    main()
